### ISSUE TITLE
Página Achievements - Ajuste na responsividade

### ISSUE THREAD

**Issue by fernandoors** [wendelfreitas/wendel.dev#4]
Olá,
Em telas médias ou inferiores as datas ficam com a mesma cor de background (white) impossibilitando a leitura.

Sugestão de código:
${media.lessThan('large')`
    .vertical-timeline-element-date {
      color: black;
    }
  `}

PS. Parabéns pelo excelente trabalho.

**Comment by wendelfreitas** [comment]
fixed ❤️
